spring:
  datasource:
    url: jdbc:mysql://:3306/zkwg?serverTimezone=Asia/Shanghai？
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
#自定义属性配置
zkwg:
  redis:
    host:
    port: 6379
    #没有密码的话 这里留空即可
    pass:
  aes:
    passkey: dP0ykNOnMdKFaXCIOnXckg==