spring:
  datasource:
    url: jdbc:mysql://:3306/zkwg?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: asd3.1415926
    #driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
#自定义属性配置
zkwg:
  redis:
    host: 192.168.65.128
    port: 6379
    #没有密码的话 这里留空即可
    pass: 123456
  aes:
    passkey: dP0ykNOnMdKFaXCIOnXckg==